<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Bold' => 'Fett',
	'Italic' => 'Kursiv',
	'Paragraph' => 'Absatz',
	'Append Line Break' => 'Zeilenumbruch anhängen',
	'Heading' => 'Überschrift',
	'Style' => 'Format',
	'URL/Link' => 'URL/Link',
	'Image' => 'Bild',
	'Indent Text' => 'Text einrücken',
	'Unindent Text' => 'Text ausrücken',
	'Bulleted List' => 'Aufzählung',
	'Numbered List' => 'Numerierte Liste',
	'Definition List' => 'Liste von Definitionem',
	'Footnote' => 'Fußnote',
	'Block Quote' => 'Zitat',
	'Inline Code' => 'Inline-Code',
	'Code Block' => 'Code-Block',
	'Horizontal Line' => 'Trennlinie',
	'Toggle full screen' => 'Vollbildmodus umschalten',
	'Save' => 'Speichern',
	'Save content' => 'Inhalt speichern',
	'Text' => 'Text',
	'HTML' => 'HTML',
	'Preview' => 'Vorausschau',
	'Preview formatted text' => 'Vorausschau für formatierten Text ',
	'No content to display' => 'Es gibt nichts anzuzeigen',
	"Your TEXT file will be generated. Save the file to your client with .txt extension in the accompanying dialog.\n\nDisable any popup blockers in your browser to ensure proper download." => "Ihre TEXT-Datei wird erzeugt. Speichern Sie die Datei auf Ihrem Rechner mit der Erweiterung .txt im nachfolgenden Dialog.\n\n Deaktivieren Sie alle Popup-Blocker in Ihrem Browser, damit das Runterladen reibungslos funktioniert." ,
	"Your HTML file will be generated. Save the file to your client with .htm/.html extension in the accompanying dialog.\n\nDisable any popup blockers in your browser to ensure proper download." => "Ihre HTML-Datei wird erzeugt. Speichern Sie die Datei auf Ihrem Rechner mit der Erweiterung .htm/.html im nachfolgenden Dialog.\n\n Deaktivieren Sie alle Popup-Blocker in Ihrem Browser, damit das Runterladen reibungslos funktioniert.",
	'Markdown Export{line} *Generated {date} by {class}' => 'Markdown Export{line} *Erzeugt am {date} von {class}',
	'Loading Preview' => 'Vorschau wird geladen',
	'PHP Markdown Extra' => 'PHP Markdown Extra',
	'PHP SmartyPants' => 'PHP SmartyPants',
	'{bullet} You may use {link} syntax.' => '{bullet} Sie können die {link} Syntax nutzen.',
	'{bullet} To undo / redo, press CTRL-Z / CTRL-Y. You can also undo most button actions by clicking it again.' => '{bullet} Um eine Aktion rückgängig zu machen/zu wiederholen, drüclem Sie Strg-Z / Strg-Y. Sie können auch die meisten Button-getriggerten Aktionen durch nochmaliges Drücken des Buttons wieder rückgängig machen.'
];