<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'and' => 'a',
    'Append Line Break' => 'Vložit konec řádku',
    'Block Quote' => 'Citace',
    'Bold' => 'Tučné písmo',
    'Bulleted List' => 'Odrážkový seznam',
    'Code Block' => 'Blok kódu',
    'CTRL-Z' => 'CTRL-Z',
    'CTRL-Y' => 'CTRL-Y',
    'Definition List' => 'Seznam definic',
    'Footnote' => 'Poznámka pod čarou',
    'HTML' => 'HTML',
    'Heading' => 'Nadpis',
    'Heading {n} Style' => 'Nadpis {n}. úrovně',
    'Horizontal Line' => 'Vodorovná čára',
    'Image' => 'Obrázek',
    'Indent Text' => 'Zarovnání textu',
    'Inline Code' => 'Inline kód',
    'Italic' => 'Kurzíva',
    'Loading Preview' => 'Načítání náhledu',
    'markdown-export' => 'markdown-export',
    'Markdown Export{line} *Generated {date} by {class}' => 'Markdown Export{line} *Vygenerovaný {date} pomocí {class}',
    'No content to display' => 'Žádný obsah k zobrazení',
    'Numbered List' => 'Číslovaný seznam',
    'PHP Markdown Extra' => 'PHP Markdown Extra',
    'PHP SmartyPants Typographer' => 'PHP SmartyPants Typographer',
    'Paragraph' => 'Odstavec',
    'Preview' => 'Náhled',
    'Preview formatted text' => 'Náhled formátovaného textu',
    'Export' => 'Export',
    'Save content' => 'Uložit obsah',
    'Save as HTML' => 'Uložit jako HTML',
    'Save as text' => 'Uložit jako text',
    'Text' => 'Text',
    'Toggle full screen' => 'Přepnout režim celé obrazovky',
    'Unindent Text' => 'Nezarovnaný text',
    'URL/Link' => 'URL/Odkaz',
    '{bullet} To undo / redo, press {keys}. You can also undo most button actions by clicking it again.' =>
        '{bullet} Pro vrácení zpět / vpřed, stiskněte {keys}. Většinu akcí tlačítek vrátíte zpět kliknutím na stejné tlačítko znovu.',
    '{bullet} You may use {link} syntax.' => '{bullet} Můžete používat {link} syntaxi.',
];
