<?php
/**
 * @package   yii2-markdown
 * @author    Kartik Visweswaran <kartikv2@gmail.com>
 * @copyright Copyright &copy; Kartik Visweswaran, Krajee.com, 2014
 * @version   1.3.0
 */

use yii\helpers\Html;

?>
<!DOCTYPE html>
<html>
<body>
<h3>DO NOT EDIT THIS FILE</h3>

<p>This view is used to generate the export download form for the Markdown editor.</p>
<?php
echo Html::beginForm();
echo Html::textInput('export_filetype', '');
echo Html::textInput('export_filename', '');
echo Html::textArea('export_content', '');
echo Html::endForm();
?>
</body>
</html>