<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'and' => 'et',
    'Append Line Break' => 'Ajouter un saut de ligne',
    'Block Quote' => 'Bloc de citation',
    'Bold' => 'Gras',
    'Bulleted List' => 'Liste à puces',
    'Code Block' => 'Bloc de code',
    'CTRL-Z' => 'CTRL-Z',
    'CTRL-Y' => 'CTRL-Y',
    'Definition List' => 'Liste de définitions',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Désactivez tout bloqueur de popup dans votre navigateur pour que les téléchargements fonctionnent correctement.',
    'Footnote' => 'Note en bas de page',
    'HTML' => 'HTML',
    'Heading' => 'En-tête',
    'Heading {n} Style' => 'En-tête de niveau {n}',
    'Horizontal Line' => 'Ligne horizontale',
    'Image' => 'Image',
    'Indent Text' => 'Identer le texte',
    'Inline Code' => 'Code inséré',
    'Italic' => 'Italique',
    'Loading Preview ' => 'Chargement de l\'aperçu ',
    'markdown-export' => 'markdown-export',
    'Markdown Export{line} *Generated {date} by {class}' => 'Export Markdown{line} *Généré le {date} par {class}',
    'No content to display' => 'Pas de contenu à afficher',
    'Numbered List' => 'Liste numérotée',
    'PHP Markdown Extra' => 'PHP Markdown Extra',
    'PHP SmartyPants Typographer' => 'PHP SmartyPants Typographer',
    'Paragraph' => 'Paragraphe',
    'Preview' => 'Aperçu',
    'Preview formatted text' => 'Aperçu du texte formaté',
    'Export' => 'Exporter',
    'Save content' => 'Sauvegarder le contenu',
    'Save as HTML' => 'Sauvegarder en HTML',
    'Save as text' => 'Sauvegarder en texte',
    'Text' => 'Texte',
    'Toggle full screen' => 'Alterner mode plein écran',
    'Unindent Text' => 'Désindenter le texte',
    'URL/Link' => 'URL/Lien',
    'Your {type} file will be generated and downloaded as {filename}.' => 'Votre fichier {type} va être généré et téléchargé comme {filename}.',
    '{bullet} To undo / redo, press {keys}. You can also undo most button actions by clicking it again.' => '{bullet} Pour annuler / rétablir, appuyez sur {keys}. Vous pouvez également annuler la plupart des actions des boutons en cliquant dessus de nouveau.',
    '{bullet} You may use {link} syntax.' => '{bullet} Vous pouvez utiliser la syntaxe : {link}'
];
