<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'and' => 'и',
    'Append Line Break' => 'Перенос строки',
    'Block Quote' => 'Цитата',
    'Bold' => 'Полужирный',
    'Bulleted List' => 'Маркированный список',
    'Code Block' => 'Код',
    'CTRL-Z' => 'CTRL-Z',
    'CTRL-Y' => 'CTRL-Y',
    'Definition List' => 'Список определений',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Отключите блокираторы всплывающих окон, чтобы быть уверенными в том, что ваш файл будет загружен.',
    'Footnote' => 'Сноска',
    'HTML' => '',
    'Heading' => 'Заголовок',
    'Heading {n} Style' => 'Заголовок {n}',
    'Horizontal Line' => 'Горизонтальная линия',
    'Image' => 'Картинка',
    'Indent Text' => 'Увеличить отступ',
    'Inline Code' => 'Код в строке',
    'Italic' => 'Наклонный',
    'Loading Preview ' => 'Загрузка предпросмотра',
    'markdown-export' => 'Сохраненный Markdown',
    'Markdown Export{line} *Generated {date} by {class}' => 'Markdown Export{line} *Создано {date} by {class}',
    'No content to display' => 'Нет содержимого',
    'Numbered List' => 'Нумерованный список',
    'PHP Markdown Extra' => '',
    'PHP SmartyPants Typographer' => '',
    'Paragraph' => 'Параграф',
    'Preview' => 'Предпросмотр',
    'Preview formatted text' => 'Предпросмотр форматированного текста',
    'Export' => 'Экспорт',
    'Save content' => 'Сохранить',
    'Save as HTML' => 'Сохранить как HTML',
    'Save as text' => 'Сохранить как текст',
    'Text' => 'текст',
    'Toggle full screen' => 'Переключить на полный экран',
    'Unindent Text' => 'Уменьшить отсутп',
    'URL/Link' => 'URL/Ссылка',
    'Your {type} file will be generated and downloaded as {filename}.' => 'Ваш {type}-файл будет сгенерирован и загружен как {filename}.',
    '{bullet} To undo / redo, press {keys}. You can also undo most button actions by clicking it again.' => '{bullet} Для отмены / повтора используйте {keys}. Вы можете отменить действие нажатой кнопки, если нажмете ее еще раз. ',
    '{bullet} You may use {link} syntax.' => '{bullet} Вы можете использовать {link} синтаксис.'
];
