<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'and' => 'e',
    'Append Line Break' => 'Aggiungi interruzione di linea',
    'Block Quote' => 'Citazione',
    'Bold' => 'Grassetto',
    'Bulleted List' => 'Elenco puntato',
    'Code Block' => 'Blocco di codice',
    'CTRL-Z' => 'CTRL-Z',
    'CTRL-Y' => 'CTRL-Y',
    'Definition List' => 'Lista definizioni',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Disabilita ogni blocco popup nel browser per permettere un corretto utilizzo.',
    'Footnote' => 'Piè di pagina',
    'HTML' => 'Html',
    'Heading' => 'Intestazione',
    'Heading {n} Style' => 'Stile di intestazione {n}',
    'Horizontal Line' => 'Linea orizzontale',
    'Image' => 'Immagine',
    'Indent Text' => 'Aumenta rientro',
    'Inline Code' => 'Codice',
    'Italic' => 'Corsivo',
    'Loading Preview ' => 'Caricamento Anteprima',
    'markdown-export' => '',
    'Markdown Export{line} *Generated {date} by {class}' => 'Markdown Export{line} *Generato il {date} da {class}',
    'No content to display' => 'Nessun contenuto da visualizzare',
    'Numbered List' => 'Elenco numerato',
    'PHP Markdown Extra' => '',
    'PHP SmartyPants Typographer' => '',
    'Paragraph' => 'Paragrafo',
    'Preview' => 'Anteprima',
    'Preview formatted text' => 'Anteprima testo formattato',
    'Export' => 'Esporta',
    'Save content' => 'Salva contenuto',
    'Save as HTML' => 'Salva come file Html',
    'Save as text' => 'Salva come file di testo',
    'Text' => 'Testo',
    'Toggle full screen' => 'A tutto schermo (apri/chiudi)',
    'Unindent Text' => 'Riduci rientro',
    'URL/Link' => 'Collegamento ipertestuale',
    'Your {type} file will be generated and downloaded as {filename}.' => 'Il tuo file {type} sarà generato e salvato come {filename}.',
    '{bullet} To undo / redo, press {keys}. You can also undo most button actions by clicking it again.' => '{bullet} Per annullare / ripristinare, premi {keys}. Puoi anche annullare molte azioni premendo di nuovo il bottone.',
    '{bullet} You may use {link} syntax.' => '{bullet} Puoi usare la sintassi {link}.'
];
