<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'and' => 'en',
    'Append Line Break' => 'Voeg regeleind toe',
    'Block Quote' => 'Blokcitaat',
    'Bold' => 'Vetgedrukt',
    'Bulleted List' => 'Opsommingstekens lijst',
    'Code Block' => 'Codeblok',
    'CTRL-Z' => 'CTRL-Z',
    'CTRL-Y' => 'CTRL-Y',
    'Definition List' => 'Definitielijst',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Schakel de pop-up blockers van uw browser uit om een correcte download the garanderen.',
    'Footnote' => 'Voetnoot',
    'HTML' => 'HTML',
    'Heading' => 'Titel',
    'Heading {n} Style' => 'Titel {n} stijl',
    'Horizontal Line' => 'Horizontale lijn',
    'Image' => 'Afbeelding',
    'Indent Text' => 'Tekst inspringen',
    'Inline Code' => 'Inline code',
    'Italic' => 'Cursief',
    'Loading Preview ' => 'Voorbeeld laden',
    'markdown-export' => 'markdown-export',
    'Markdown Export{line} *Generated {date} by {class}' => 'Markdown Export{line} *Gegenereerd {date} door {class}',
    'No content to display' => 'Geen inhoud om te tonen',
    'Numbered List' => 'Genummerde lijst',
    'PHP Markdown Extra' => 'PHP Markdown Extra',
    'PHP SmartyPants Typographer' => 'PHP SmartyPants Typographer',
    'Paragraph' => 'Paragraaf',
    'Preview' => 'Voorbeeld',
    'Preview formatted text' => 'Voorbeeld opgemaakte tekst',
    'Export' => 'Exporteren',
    'Save content' => 'Inhoud opslaan',
    'Save as HTML' => 'Sla op als HTML',
    'Save as text' => 'Sla op als tekst',
    'Text' => 'Tekst',
    'Toggle full screen' => 'Schakel naar volledig scherm',
    'Unindent Text' => 'Niet ingesprongen tekst',
    'URL/Link' => 'URL/link',
    'Your {type} file will be generated and downloaded as {filename}.' => 'Uw {type} bestand zal worden gegenereerd en gedownload als {filename}.',
    '{bullet} To undo / redo, press {keys}. You can also undo most button actions by clicking it again.' => '{bullet} Om gedaan / ongedaan te maken, druk {keys}. U kunt ook de meeste knop acties ongedaan maken door nog een keer op de knop te klikken.',
    '{bullet} You may use {link} syntax.' => '{bullet} U mag de {link} syntax gebruiken.'
];
