<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'and' => 'і',
    'Append Line Break' => 'Перенесення рядка',
    'Block Quote' => 'Цитата',
    'Bold' => 'Напівжирний',
    'Bulleted List' => 'Маркований список',
    'Code Block' => 'Код',
    'CTRL-Z' => 'CTRL-Z',
    'CTRL-Y' => 'CTRL-Y',
    'Definition List' => 'Список визначень',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Вимкніть блокіратори спливаючих вікон, щоб бути впевненими в тому, що ваш файл буде завантажений.',
    'Footnote' => 'Виноска',
    'HTML' => '',
    'Heading' => 'Заголовок',
    'Heading {n} Style' => 'Заголовок {n}',
    'Horizontal Line' => 'Горизонтальна лінія',
    'Image' => 'Картинка',
    'Indent Text' => 'Збільшити відступ',
    'Inline Code' => 'Код в рядку',
    'Italic' => 'Похилий',
    'Loading Preview ' => 'Завантаження преперегляду',
    'markdown-export' => 'Збережений Markdown',
    'Markdown Export{line} *Generated {date} by {class}' => 'Markdown Export{line} *Створено {date} by {class}',
    'No content to display' => 'Відсутній зміст',
    'Numbered List' => 'Нумерований список',
    'PHP Markdown Extra' => '',
    'PHP SmartyPants Typographer' => '',
    'Paragraph' => 'Параграф',
    'Preview' => 'Преперегляд',
    'Preview formatted text' => 'Преперегляд форматованого тексту',
    'Export' => 'Експорт',
    'Save content' => 'Зберегти',
    'Save as HTML' => 'Зберегти як HTML',
    'Save as text' => 'Зберегти як текст',
    'Text' => 'текст',
    'Toggle full screen' => 'Перемкнути на повний екран',
    'Unindent Text' => 'Зменьшити відступ',
    'URL/Link' => 'URL/Посилання',
    'Your {type} file will be generated and downloaded as {filename}.' => 'Ваш {type}-файл буде згенеровано і завантажено як {filename}.',
    '{bullet} To undo / redo, press {keys}. You can also undo most button actions by clicking it again.' => '{bullet} Для відміни / повтору використовуйте {keys}. Ви можете відмінити дію натиском кнопки, якщо натиснете її ще раз. ',
    '{bullet} You may use {link} syntax.' => '{bullet} Ви можете використовувати {link} синтаксис.'
];
