<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'and' => 'és',
    'Append Line Break' => 'Soremelés',
    'Block Quote' => 'Idézet',
    'Bold' => 'Félkövér',
    'Bulleted List' => 'Felsorolás',
    'Code Block' => 'Kód blokk',
    'CTRL-Z' => 'CTRL-Z',
    'CTRL-Y' => 'CTRL-Y',
    'Definition List' => 'Meghatározás lista',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Engedélyezd a felugró ablakokat a böngészőjében, a sikeres letöltés érdekében.',
    'Footnote' => 'Lábjegyzet',
    'HTML' => 'HTML',
    'Heading' => 'Cím',
    'Heading {n} Style' => 'Cím {n} stílus',
    'Horizontal Line' => 'Vízszintes vonal',
    'Image' => 'Kép',
    'Indent Text' => 'Szöveg behúzás',
    'Inline Code' => 'Inline Kód',
    'Italic' => 'Dőlt',
    'Loading Preview ' => 'Előnézet betöltés',
    'markdown-export' => 'markdown-export',
    'Markdown Export{line} *Generated {date} by {class}' => '',
    'No content to display' => 'Nincs megjeleníthető tartalom',
    'Numbered List' => 'Számozás',
    'PHP Markdown Extra' => 'PHP Markdown Extra',
    'PHP SmartyPants Typographer' => 'PHP SmartyPants Typographer',
    'Paragraph' => 'Bekezdés',
    'Preview' => 'Előnézet',
    'Preview formatted text' => 'Formázott szöveg előnézete',
    'Export' => 'Export',
    'Save content' => 'Tartalom mentése',
    'Save as HTML' => 'Mentés HTML-ként ',
    'Save as text' => 'Mentés szövegként',
    'Text' => 'Szöveg',
    'Toggle full screen' => 'Váltás teljes képernyőre',
    'Unindent Text' => 'Szöveg behúzás megszüntetése',
    'URL/Link' => 'URL/Hivatkozás',
    'Your {type} file will be generated and downloaded as {filename}.' => '',
    '{bullet} To undo / redo, press {keys}. You can also undo most button actions by clicking it again.' => '{bullet} Visszavonáshoz / Ismétléshez használd a {keys} billentyűket. A legtöbb esetben a gomb újra lenyomással is vissza tudzs vonni.',
    '{bullet} You may use {link} syntax.' => '{bullet} Használhatod a {link} formátumokat is.'
];
