<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'and' => 'i',
    'Append Line Break' => 'Dodaj Linię Przerywaną',
    'Block Quote' => 'Cytat',
    'Bold' => 'Pogrubienie',
    'Bulleted List' => 'Lista punktowana',
    'Code Block' => 'Code Block',
    'CTRL-Z' => 'CTRL-Z',
    'CTRL-Y' => 'CTRL-Y',
    'Definition List' => 'Lista Definicji',
    'Footnote' => 'Notatka',
    'HTML' => 'HTML',
    'Heading' => 'Nagłówek',
    'Heading {n} Style' => '{n} styl nagłówka',
    'Horizontal Line' => 'Linia pozioma',
    'Image' => 'Obraz',
    'Indent Text' => 'Akapit',
    'Inline Code' => 'Inline Code',
    'Italic' => 'Kursywa',
    'Loading Preview ' => 'Ładowanie podglądu',
    'markdown-export' => 'markdown-export',
    'Markdown Export{line} *Generated {date} by {class}' => 'Markdown Export{line} *Wygenerowany {date} przez {class}',
    'No content to display' => 'Brak zawartości do wyświetlenia',
    'Numbered List' => 'Ponumerowana lista',
    'PHP Markdown Extra' => 'PHP Markdown Extra',
    'PHP SmartyPants Typographer' => 'PHP SmartyPants Typographer',
    'Paragraph' => 'Paragraf',
    'Preview' => 'Podgląd',
    'Preview formatted text' => 'Podgląd sformatowanego tekstu',
    'Export' => 'Eksportuj',
    'Save content' => 'Zapisz zawartość',
    'Save as HTML' => 'Zapisz jako HTML',
    'Save as text' => 'Zapisz jako tekst',
    'Text' => 'Tekst',
    'Toggle full screen' => 'Przełącz na tryb pełnoekranowy',
    'Unindent Text' => 'Bez akapitu',
    'URL/Link' => 'URL/Link',
    '{bullet} To undo / redo, press {keys}. You can also undo most button actions by clicking it again.' => '{bullet} Aby cofnąć/zrobić ponownie, naciśnij {keys}. Możesz również cofnąć więcej akcji poprzez kliknięcie ponownie przycisku.',
    '{bullet} You may use {link} syntax.' => '{bullet} Możesz użyć {link} składnię.',
];
