<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'and' => '',
    'Append Line Break' => '',
    'Block Quote' => '',
    'Bold' => '',
    'Bulleted List' => '',
    'Code Block' => '',
    'CTRL-Z' => 'CTRL-Z',
    'CTRL-Y' => 'CTRL-Y',
    'Definition List' => '',
    'Disable any popup blockers in your browser to ensure proper download.' => '',
    'Footnote' => '',
    'HTML' => '',
    'Heading' => '',
    'Heading {n} Style' => '',
    'Horizontal Line' => '',
    'Image' => '',
    'Indent Text' => '',
    'Inline Code' => '',
    'Italic' => '',
    'Loading Preview ' => '',
    'markdown-export' => '',
    'Markdown Export{line} *Generated {date} by {class}' => '',
    'No content to display' => '',
    'Numbered List' => '',
    'PHP Markdown Extra' => '',
    'PHP SmartyPants Typographer' => '',
    'Paragraph' => '',
    'Preview' => '',
    'Preview formatted text' => '',
    'Export' => '',
    'Save content' => '',
    'Save as HTML' => '',
    'Save as text' => '',
    'Text' => '',
    'Toggle full screen' => '',
    'Unindent Text' => '',
    'URL/Link' => '',
    'Your {type} file will be generated and downloaded as {filename}.' => '',
    '{bullet} To undo / redo, press {keys}. You can also undo most button actions by clicking it again.' => '',
    '{bullet} You may use {link} syntax.' => ''
];
