<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Bold' => 'Bold',
	'Italic' => 'Italic',
	'Paragraph' => 'Paragraph',
	'Append Line Break' => 'Append Line Break',
	'Heading' => 'Heading',
	'Style' => 'Style',
	'URL/Link' => 'URL/Link',
	'Image' => 'Image',
	'Indent Text' => 'Indent Text',
	'Unindent Text' => 'Unindent Text',
	'Bulleted List' => 'Bulleted List',
	'Numbered List' => 'Numbered List',
	'Definition List' => 'Definition List',
	'Footnote' => 'Footnote',
	'Block Quote' => 'Block Quote',
	'Inline Code' => 'Inline Code',
	'Code Block' => 'Code Block',
	'Horizontal Line' => 'Horizontal Line',
	'Toggle full screen' => 'Toggle full screen',
	'Save' => 'Save',
	'Save content' => 'Save content',
	'Text' => 'Text',
	'HTML' => 'HTML',
	'Preview' => 'Preview',
	'Preview formatted text' => 'Preview formatted text',
	'No content to display' => 'No content to display',
	"Your TEXT file will be generated. Save the file to your client with .txt extension in the accompanying dialog.\n\nDisable any popup blockers in your browser to ensure proper download." => "Your TEXT file will be generated. Save the file to your client with .txt extension in the accompanying dialog.\n\n Disable any popup blockers in your browser to ensure proper download." ,
	"Your HTML file will be generated. Save the file to your client with .htm/.html extension in the accompanying dialog.\n\nDisable any popup blockers in your browser to ensure proper download." => "Your HTML file will be generated. Save the file to your client with .htm/.html extension in the accompanying dialog.\n\nDisable any popup blockers in your browser to ensure proper download.",
	'Markdown Export{line} *Generated {date} by {class}' => 'Markdown Export{line} *Generated {date} by {class}',
	'Loading Preview' => 'Loading Preview',
	'PHP Markdown Extra' => 'PHP Markdown Extra',
	'PHP SmartyPants' => 'PHP SmartyPants',
	'{bullet} You may use {link} syntax.' => '{bullet} You may use {link} syntax.',
	'{bullet} To undo / redo, press CTRL-Z / CTRL-Y. You can also undo most button actions by clicking it again.' => '{bullet} To undo / redo, press CTRL-Z / CTRL-Y. You can also undo most button actions by clicking it again.'
];