<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 * @author Vikramk Khot <khotvikramk1991@gmail.com>
 */
return [
    'and' => 'आणि',
    'Append Line Break' => 'लाइन ब्रेक जोडा',
    'Block Quote' => 'ब्लॉक कोट',
    'Bold' => 'ठळक',
    'Bulleted List' => 'बुलेटेड सूची',
    'Code Block' => 'कोड ब्लॉक',
    'CTRL-Z' => 'CTRL-Z',
    'CTRL-Y' => 'CTRL-Y',
    'Definition List' => '',
    'Footnote' => 'तळटीप',
    'HTML' => 'HTML',
    'Heading' => 'शिर्षक',
    'Heading {n} Style' => 'मथळा {n} शैली',
    'Horizontal Line' => 'क्षैतिज रेखा',
    'Image' => 'प्रतिमा',
    'Indent Text' => 'इंडेंट मजकूर',
    'Inline Code' => 'इनलाइन कोड',
    'Italic' => 'तिर्यक',
    'Loading Preview ' => 'पूर्वावलोकन लोड करत आहे',
    'markdown-export' => 'Markdown निर्यात',
    'Markdown Export{line} *Generated {date} by {class}' => 'मार्कडाउन एक्सपोर्ट {line} * {class} ने {class} तयार केले',
    'No content to display' => 'प्रदर्शित करण्यासाठी कोणतीही सामग्री नाही',
    'Numbered List' => 'क्रमांकित सूची',
    'PHP Markdown Extra' => 'PHP मार्कडाउन एक्स्ट्रा',
    'PHP SmartyPants Typographer' => 'PHP स्मार्टीपंटस टाईपोग्राफर',
    'Paragraph' => 'परिच्छेद',
    'Preview' => 'पूर्वावलोकन',
    'Preview formatted text' => 'पूर्वावलोकन स्वरूपित मजकूर',
    'Export' => 'निर्यात',
    'Save content' => 'सामग्री जतन करा',
    'Save as HTML' => 'HTML म्हणून जतन करा',
    'Save as text' => 'मजकूर म्हणून जतन करा',
    'Text' => 'मजकूर',
    'Toggle full screen' => 'पूर्ण स्क्रीन टॉगल करा',
    'Unindent Text' => 'अशीर्षकांकित मजकूर',
    'URL/Link' => 'URL / दुवा',
    '{bullet} To undo / redo, press {keys}. You can also undo most button actions by clicking it again.' => '{bullet} पूर्ववत / पुन्हा करण्यासाठी, {की} दाबा आपण देखील आपल्या बाहेरील कंद खाली ठेवू शकता',
    '{bullet} You may use {link} syntax.' => '{bullet} आपण {link} वाक्यरचना वापरू शकता'
];
