<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'Append Line Break' => 'Zeilenumbruch anhängen',
    'Block Quote' => 'Zitat',
    'Bold' => 'Fett',
    'Bulleted List' => 'Aufzählung',
    'Code Block' => 'Code-Block',
    'Definition List' => 'Liste von Definitionem',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Deaktivieren Sie alle Popup-Blocker in Ihrem Browser, damit das Runterladen reibungslos funktioniert.',
    'Footnote' => 'Fußnote',
    'HTML' => 'HTML',
    'Heading' => 'Überschrift',
    'Heading {n} Style' => 'Überschrift {n} Format',
    'Horizontal Line' => 'Trennlinie',
    'Image' => 'Bild',
    'Indent Text' => 'Text einrücken',
    'Inline Code' => 'Inline-Code',
    'Italic' => 'Kursiv',
    'Loading Preview' => 'Vorschau wird geladen',
    'Markdown Export{line} *Generated {date} by {class}' => 'Markdown Export{line} *Erzeugt am {date} von {class}',
    'No content to display' => 'Es gibt nichts anzuzeigen',
    'Numbered List' => 'Numerierte Liste',
    'PHP Markdown Extra' => 'PHP Markdown Extra',
    'PHP SmartyPants' => 'PHP SmartyPants',
    'Paragraph' => 'Absatz',
    'Preview' => 'Vorausschau',
    'Preview formatted text' => 'Vorausschau für formatierten Text ',
    'Save' => 'Speichern',
    'Save content' => 'Inhalt speichern',
    'Save as HTML' => 'Speichern HTML',
    'Save as text' => 'Speichern text',
    'Text' => 'Text',
    'Toggle full screen' => 'Vollbildmodus umschalten',
    'Unindent Text' => 'Text ausrücken',
    'URL/Link' => 'URL/Link',
    'Your {type} file will be generated. Save the file to your client with {ext} extension in the accompanying dialog.' => 'Ihre {type}-Datei wird erzeugt. Speichern Sie die Datei auf Ihrem Rechner mit der Erweiterung .htm/.html im nachfolgenden Dialog.',
    '{bullet} You may use {link} syntax.' => '{bullet} Sie können die {link} Syntax nutzen.',
    '{bullet} To undo / redo, press CTRL-Z / CTRL-Y. You can also undo most button actions by clicking it again.' => '{bullet} Um Undo / Redo, drücken Sie STRG-Z / STRG-Y. Sie können auch rückgängig machen meisten Button-Aktionen durch erneutes Anklicken.',
);
