<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'and' => 'und',
    'Append Line Break' => 'Zeilenumbruch anhängen',
    'Block Quote' => 'Zitat',
    'Bold' => 'Fett',
    'Bulleted List' => 'Aufzählung',
    'Code Block' => 'Code-Block',
    'CTRL-Z' => 'STRG-Z',
    'CTRL-Y' => 'STRG-Y',
    'Definition List' => 'Liste von Definitionen',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Deaktivieren Sie alle Popup-Blocker in Ihrem Browser, damit das Runterladen reibungslos funktioniert.',
    'Footnote' => 'Fußnote',
    'HTML' => 'HTML',
    'Heading' => 'Überschrift',
    'Heading {n} Style' => 'Überschrift {n} Format',
    'Horizontal Line' => 'Trennlinie',
    'Image' => 'Bild',
    'Indent Text' => 'Text einrücken',
    'Inline Code' => 'Inline-Code',
    'Italic' => 'Kursiv',
    'Loading Preview' => 'Vorschau wird geladen',
    'markdown-export' => 'markdown-export',
    'Markdown Export{line} *Generated {date} by {class}' => 'Markdown Export{line} *Erzeugt am {date} von {class}',
    'No content to display' => 'Es gibt nichts anzuzeigen',
    'Numbered List' => 'Numerierte Liste',
    'PHP Markdown Extra' => 'PHP Markdown Extra',
    'PHP SmartyPants Typographer' => 'PHP SmartyPants Typographer',
    'Paragraph' => 'Absatz',
    'Preview' => 'Vorausschau',
    'Preview formatted text' => 'Vorausschau für formatierten Text ',
    'Export' => 'Export',
    'Export content' => 'Export Inhalt',
    'Save as HTML' => 'Speichern als HTML',
    'Save as text' => 'Speichern als Text',
    'Text' => 'Text',
    'Toggle full screen' => 'In Vollbildmodus umschalten',
    'Unindent Text' => 'Text ausrücken',
    'URL/Link' => 'URL/Link',
    'Your {type} file will be generated and downloaded as {filename}.' => 'Ihre {type}-Datei wird erzeugt und als {filename} heruntergeladen werden.',
    '{bullet} To undo / redo, press {keys}. You can also undo most button actions by clicking it again.' => '{bullet} Rückgängig machen/Wiederherstellen via {keys}. Die meisten Button-Aktionen können Sie auch durch erneutes Anklicken rückgängig machen.',
    '{bullet} You may use {link} syntax.' => '{bullet} Sie können die {link} Syntax nutzen.'
];